# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/gumwork" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Social
twitter_username: jekyllrb
github_username:  jekyll
behance_username: gumwork
vimeo_username: gumwork
instagram_username: gumwork

# Build settings
markdown: kramdown
